[[themes]]
name = "matugen"

[themes.component_style]
block_title = { fg = "{{colors.primary.default.hex}}", modifiers = ["Bold"] }
border = { fg = "{{colors.outline.default.hex}}" }

playback_status = { fg = "{{colors.primary.default.hex}}", modifiers = ["Bold"] }
playback_track = { fg = "{{colors.on_surface.default.hex}}", modifiers = ["Bold"] }
playback_artists = { fg = "{{colors.secondary.default.hex}}" }
playback_album = { fg = "{{colors.tertiary.default.hex}}" }
playback_genres = { fg = "{{colors.on_surface_variant.default.hex}}", modifiers = ["Italic"] }
playback_metadata = { fg = "{{colors.on_surface_variant.default.hex}}" }
playback_progress_bar = { fg = "{{colors.primary.default.hex}}", bg = "{{colors.surface_container_highest.default.hex}}" }
playback_progress_bar_unfilled = { bg = "{{colors.surface_container_highest.default.hex}}" }

current_playing = { fg = "{{colors.primary.default.hex}}", modifiers = ["Bold"] }
page_desc = { fg = "{{colors.secondary.default.hex}}", modifiers = ["Bold"] }
playlist_desc = { fg = "{{colors.on_surface_variant.default.hex}}", modifiers = ["Dim"] }
table_header = { fg = "{{colors.tertiary.default.hex}}" }
selection = { fg = "{{colors.on_secondary_container.default.hex}}", bg = "{{colors.secondary_container.default.hex}}" }

secondary_row = { fg = "{{colors.outline.default.hex}}" }
like = { fg = "{{colors.tertiary.default.hex}}" }
lyrics_played = { fg = "{{colors.outline.default.hex}}", modifiers = ["Dim"] }
lyrics_playing = { fg = "{{colors.primary.default.hex}}", modifiers = ["Bold"] }
