$image = /home/m_frost/Pictures/Wallpaper/wallz/Catppuccin Mocha/10. Catppuccin Mocha.png

$background = rgba(3b3858ff)

$error = rgba(ffdcd7ff)

$error_container = rgba(ff796aff)

$inverse_on_surface = rgba(43435cff)

$inverse_primary = rgba(3f00ffff)

$inverse_surface = rgba(e8e4f4ff)

$on_background = rgba(e8e4f4ff)

$on_error = rgba(c60006ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(1f00d6ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(2e00ffff)

$on_secondary = rgba(462f74ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(59467dff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(efecfcff)

$on_tertiary = rgba(591e79ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(693a82ff)

$outline = rgba(cbc8d7ff)

$outline_variant = rgba(aeabbaff)

$primary = rgba(e4e1ffff)

$primary_container = rgba(9c99ffff)

$primary_fixed = rgba(e5e2ffff)

$primary_fixed_dim = rgba(cac7ffff)

$scrim = rgba(000000ff)

$secondary = rgba(ecddffff)

$secondary_container = rgba(b3a4ceff)

$secondary_fixed = rgba(eee0ffff)

$secondary_fixed_dim = rgba(d7c8f1ff)

$shadow = rgba(000000ff)

$source_color = rgba(3b3a5aff)

$surface = rgba(3b3858ff)

$surface_bright = rgba(696678ff)

$surface_container = rgba(504e63ff)

$surface_container_high = rgba(59586bff)

$surface_container_highest = rgba(626174ff)

$surface_container_low = rgba(44445cff)

$surface_container_lowest = rgba(232364ff)

$surface_dim = rgba(3b3858ff)

$surface_tint = rgba(cac7ffff)

$surface_variant = rgba(696678ff)

$tertiary = rgba(f7d9ffff)

$tertiary_container = rgba(c29cd4ff)

$tertiary_fixed = rgba(f8dbffff)

$tertiary_fixed_dim = rgba(e7bff7ff)

