$image = /home/m_frost/Pictures/Wallpaper/wallz/Solarized Dark/12. Solarized Dark.jpg

$background = rgba(2d4553ff)

$error = rgba(ffdcd7ff)

$error_container = rgba(ff796aff)

$inverse_on_surface = rgba(3a4c56ff)

$inverse_primary = rgba(967e00ff)

$inverse_surface = rgba(e1e8eeff)

$on_background = rgba(e1e8eeff)

$on_error = rgba(c60006ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(6e5900ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(806900ff)

$on_secondary = rgba(4d2d71ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(5e447aff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(e3f1fbff)

$on_tertiary = rgba(00557cff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(006891ff)

$outline = rgba(becdd7ff)

$outline_variant = rgba(a1b1bbff)

$primary = rgba(ffec81ff)

$primary_container = rgba(cfb748ff)

$primary_fixed = rgba(ffee82ff)

$primary_fixed_dim = rgba(f0d86dff)

$scrim = rgba(000000ff)

$secondary = rgba(f0dbffff)

$secondary_container = rgba(b7a2ccff)

$secondary_fixed = rgba(f2deffff)

$secondary_fixed_dim = rgba(dbc7efff)

$shadow = rgba(000000ff)

$source_color = rgba(0e3741ff)

$surface = rgba(2d4553ff)

$surface_bright = rgba(626d74ff)

$surface_container = rgba(47555fff)

$surface_container_high = rgba(515e66ff)

$surface_container_highest = rgba(5b666eff)

$surface_container_low = rgba(3c4d57ff)

$surface_container_lowest = rgba(113d58ff)

$surface_dim = rgba(2d4553ff)

$surface_tint = rgba(f0d86dff)

$surface_variant = rgba(5b6d79ff)

$tertiary = rgba(c2ecffff)

$tertiary_container = rgba(7ab6d8ff)

$tertiary_fixed = rgba(c7edffff)

$tertiary_fixed_dim = rgba(a0d9faff)

