[[themes]]
name = "matugen"

[themes.component_style]
block_title = { fg = "#cccadb", modifiers = ["Bold"] }
border = { fg = "#aaa8aa" }

playback_status = { fg = "#cccadb", modifiers = ["Bold"] }
playback_track = { fg = "#f8f3f6", modifiers = ["Bold"] }
playback_artists = { fg = "#cdcad5" }
playback_album = { fg = "#cac8e2" }
playback_genres = { fg = "#cecacc", modifiers = ["Italic"] }
playback_metadata = { fg = "#cecacc" }
playback_progress_bar = { fg = "#cccadb", bg = "#4e4d4e" }
playback_progress_bar_unfilled = { bg = "#4e4d4e" }

current_playing = { fg = "#cccadb", modifiers = ["Bold"] }
page_desc = { fg = "#cdcad5", modifiers = ["Bold"] }
playlist_desc = { fg = "#cecacc", modifiers = ["Dim"] }
table_header = { fg = "#cac8e2" }
selection = { fg = "#ffffff", bg = "#82808b" }

secondary_row = { fg = "#aaa8aa" }
like = { fg = "#cac8e2" }
lyrics_played = { fg = "#aaa8aa", modifiers = ["Dim"] }
lyrics_playing = { fg = "#cccadb", modifiers = ["Bold"] }
