[[themes]]
name = "matugen"

[themes.component_style]
block_title = { fg = "#e7e5ec", modifiers = ["Bold"] }
border = { fg = "#d1ced5" }

playback_status = { fg = "#e7e5ec", modifiers = ["Bold"] }
playback_track = { fg = "#ffffff", modifiers = ["Bold"] }
playback_artists = { fg = "#e8e5e8" }
playback_album = { fg = "#f0e4d8" }
playback_genres = { fg = "#fcfaff", modifiers = ["Italic"] }
playback_metadata = { fg = "#fcfaff" }
playback_progress_bar = { fg = "#e7e5ec", bg = "#555353" }
playback_progress_bar_unfilled = { bg = "#555353" }

current_playing = { fg = "#e7e5ec", modifiers = ["Bold"] }
page_desc = { fg = "#e8e5e8", modifiers = ["Bold"] }
playlist_desc = { fg = "#fcfaff", modifiers = ["Dim"] }
table_header = { fg = "#f0e4d8" }
selection = { fg = "#000000", bg = "#aeacb0" }

secondary_row = { fg = "#d1ced5" }
like = { fg = "#f0e4d8" }
lyrics_played = { fg = "#d1ced5", modifiers = ["Dim"] }
lyrics_playing = { fg = "#e7e5ec", modifiers = ["Bold"] }
