$image = Null

$background = rgba(2b292bff)

$error = rgba(ffdedaff)

$error_container = rgba(ff8477ff)

$inverse_on_surface = rgba(232326ff)

$inverse_primary = rgba(585860ff)

$inverse_surface = rgba(e7e4e4ff)

$on_background = rgba(e7e4e4ff)

$on_error = rgba(6e0002ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(212330ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(3b3b44ff)

$on_secondary = rgba(24242aff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(3d3b40ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(fcfaffff)

$on_tertiary = rgba(332814ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(453d30ff)

$outline = rgba(d1ced5ff)

$outline_variant = rgba(adacb2ff)

$primary = rgba(e7e5ecff)

$primary_container = rgba(adacb4ff)

$primary_fixed = rgba(e5e3eaff)

$primary_fixed_dim = rgba(cccbd1ff)

$scrim = rgba(000000ff)

$secondary = rgba(e8e5e8ff)

$secondary_container = rgba(aeacb0ff)

$secondary_fixed = rgba(e6e4e6ff)

$secondary_fixed_dim = rgba(cdcbcdff)

$shadow = rgba(000000ff)

$source_color = rgba(616167ff)

$surface = rgba(2b292bff)

$surface_bright = rgba(5c5b5bff)

$surface_container = rgba(414040ff)

$surface_container_high = rgba(4b4949ff)

$surface_container_highest = rgba(555353ff)

$surface_container_low = rgba(353335ff)

$surface_container_lowest = rgba(1b1b21ff)

$surface_dim = rgba(2b292bff)

$surface_tint = rgba(cccbd1ff)

$surface_variant = rgba(57575eff)

$tertiary = rgba(f0e4d8ff)

$tertiary_container = rgba(b5ada0ff)

$tertiary_fixed = rgba(eee4d6ff)

$tertiary_fixed_dim = rgba(d5cabeff)

