$image = /home/m_frost/Pictures/Wallpaper/wallz/Catppuccin Mocha/24. Catppuccin Mocha.jpg

$background = rgba(3b3858ff)

$error = rgba(ffd8d1ff)

$error_container = rgba(ff6255ff)

$inverse_on_surface = rgba(514f64ff)

$inverse_primary = rgba(4500ffff)

$inverse_surface = rgba(e8e4f4ff)

$on_background = rgba(e8e4f4ff)

$on_error = rgba(d60007ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(2c00ebff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(1a00c1ff)

$on_primary_fixed_variant = rgba(3900ffff)

$on_secondary = rgba(523d78ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(3f1f75ff)

$on_secondary_fixed_variant = rgba(604d81ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(e4dfefff)

$on_tertiary = rgba(612e7dff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(54087cff)

$on_tertiary_fixed_variant = rgba(6f4285ff)

$outline = rgba(c1becdff)

$outline_variant = rgba(a5a3b2ff)

$primary = rgba(e0dcffff)

$primary_container = rgba(948dffff)

$primary_fixed = rgba(e6e2ffff)

$primary_fixed_dim = rgba(cbc7ffff)

$scrim = rgba(000000ff)

$secondary = rgba(ead9ffff)

$secondary_container = rgba(ac9bc6ff)

$secondary_fixed = rgba(eedfffff)

$secondary_fixed_dim = rgba(d8c8f1ff)

$shadow = rgba(000000ff)

$source_color = rgba(6c6a7bff)

$surface = rgba(3b3858ff)

$surface_bright = rgba(676577ff)

$surface_container = rgba(4f4d61ff)

$surface_container_high = rgba(585669ff)

$surface_container_highest = rgba(625f72ff)

$surface_container_low = rgba(45435dff)

$surface_container_lowest = rgba(29295eff)

$surface_dim = rgba(3b3858ff)

$surface_tint = rgba(cbc7ffff)

$surface_variant = rgba(696678ff)

$tertiary = rgba(f6d4ffff)

$tertiary_container = rgba(ba93cbff)

$tertiary_fixed = rgba(f9dbffff)

$tertiary_fixed_dim = rgba(e7bff6ff)

