-- Colors configuration for Hyprland (ported from colors.conf)

colors = {
    image = "/home/m_frost/Pictures/Wallpaper/walls-main/flowers/a_group_of_red_flowers_01.jpg",
    background = "rgba(2a2a2aff)",
    error = "rgba(ffdedaff)",
    error_container = "rgba(ff8477ff)",
    inverse_on_surface = "rgba(242424ff)",
    inverse_primary = "rgba(9e353eff)",
    inverse_surface = "rgba(e4e4e4ff)",
    on_background = "rgba(e4e4e4ff)",
    on_error = "rgba(6e0002ff)",
    on_error_container = "rgba(000000ff)",
    on_primary = "rgba(69000aff)",
    on_primary_container = "rgba(000000ff)",
    on_primary_fixed = "rgba(000000ff)",
    on_primary_fixed_variant = "rgba(830c21ff)",
    on_secondary = "rgba(4a1417ff)",
    on_secondary_container = "rgba(000000ff)",
    on_secondary_fixed = "rgba(000000ff)",
    on_secondary_fixed_variant = "rgba(573133ff)",
    on_surface = "rgba(ffffffff)",
    on_surface_variant = "rgba(fbfbfbff)",
    on_tertiary = "rgba(462500ff)",
    on_tertiary_container = "rgba(000000ff)",
    on_tertiary_fixed = "rgba(000000ff)",
    on_tertiary_fixed_variant = "rgba(623e00ff)",
    outline = "rgba(d0d0d0ff)",
    outline_variant = "rgba(adadadff)",
    primary = "rgba(ffdedeff)",
    primary_container = "rgba(fe8a90ff)",
    primary_fixed = "rgba(ffdcdcff)",
    primary_fixed_dim = "rgba(ffb7b8ff)",
    scrim = "rgba(000000ff)",
    secondary = "rgba(ffdedeff)",
    secondary_container = "rgba(cba2a4ff)",
    secondary_fixed = "rgba(ffdcdcff)",
    secondary_fixed_dim = "rgba(ebc1c1ff)",
    shadow = "rgba(000000ff)",
    source_color = "rgba(ba233bff)",
    surface = "rgba(2a2a2aff)",
    surface_bright = "rgba(5b5b5bff)",
    surface_container = "rgba(404040ff)",
    surface_container_high = "rgba(4a4a4aff)",
    surface_container_highest = "rgba(535353ff)",
    surface_container_low = "rgba(343434ff)",
    surface_container_lowest = "rgba(1d1d1dff)",
    surface_dim = "rgba(2a2a2aff)",
    surface_tint = "rgba(ffb7b8ff)",
    surface_variant = "rgba(595959ff)",
    tertiary = "rgba(ffe2b7ff)",
    tertiary_container = "rgba(cea975ff)",
    tertiary_fixed = "rgba(ffe0b3ff)",
    tertiary_fixed_dim = "rgba(eec792ff)",
}

return colors
