$image = /home/m_frost/Pictures/Wallpaper/wallz/Dracula/04. Dracula.png

$background = rgba(2b435aff)

$error = rgba(ffd8d1ff)

$error_container = rgba(ff6255ff)

$inverse_on_surface = rgba(455565ff)

$inverse_primary = rgba(0078bcff)

$inverse_surface = rgba(e1e8f3ff)

$on_background = rgba(e1e8f3ff)

$on_error = rgba(d60007ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(005994ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(00437fff)

$on_primary_fixed_variant = rgba(0068a6ff)

$on_secondary = rgba(2c4b84ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(033590ff)

$on_secondary_fixed_variant = rgba(42598aff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(dce3edff)

$on_tertiary = rgba(363e93ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(141ca3ff)

$on_tertiary_fixed_variant = rgba(494f99ff)

$outline = rgba(b9c2ccff)

$outline_variant = rgba(9da6b2ff)

$primary = rgba(c7e5ffff)

$primary_container = rgba(00b6ffff)

$primary_fixed = rgba(d1eaffff)

$primary_fixed_dim = rgba(9cd6ffff)

$scrim = rgba(000000ff)

$secondary = rgba(d3e1ffff)

$secondary_container = rgba(93a4caff)

$secondary_fixed = rgba(dce6ffff)

$secondary_fixed_dim = rgba(c0cff5ff)

$shadow = rgba(000000ff)

$source_color = rgba(15222eff)

$surface = rgba(2b435aff)

$surface_bright = rgba(5e6977ff)

$surface_container = rgba(435462ff)

$surface_container_high = rgba(4e5b69ff)

$surface_container_highest = rgba(586472ff)

$surface_container_low = rgba(394a5eff)

$surface_container_lowest = rgba(143564ff)

$surface_dim = rgba(2b435aff)

$surface_tint = rgba(9cd6ffff)

$surface_variant = rgba(606b78ff)

$tertiary = rgba(ddddffff)

$tertiary_container = rgba(9a9ed9ff)

$tertiary_fixed = rgba(e3e3ffff)

$tertiary_fixed_dim = rgba(c6c9ffff)

