general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn screen on after wake
    inhibit_sleep = 3                           # wait until session is locked before sleeping to prevent unlocked desktop flash
}

# 1. Lock screen (600s / 10 min)
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 2. Turn off display (660s / 11 min)
listener {
    timeout = 660
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 3. Suspend system (900s / 15 min)
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
