-- Generated by HyprMod (ported from hyprland-gui.conf)

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")

-- Bezier curves
hl.curve("custom1", { type = "bezier", points = { {0.0, 0.029}, {0.474, 0.997} } })
hl.curve("easeOutQuad", { type = "bezier", points = { {0.5, 1.0}, {0.89, 1.0} } })

-- Animations
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuad", style = "gnomed" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 3.2, bezier = "custom1", style = "slidefade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "custom1", style = "slidevert" })

-- Keybinds
hl.unbind("SUPER + SHIFT + J")
hl.unbind("SUPER + SHIFT + L")
hl.unbind("SUPER + SHIFT + K")
hl.unbind("SUPER + SHIFT + H")

hl.bind("SUPER + F1", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("SUPER + SHIFT + L", hl.dsp.window.move({ direction = "right" }))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
hl.bind("SUPER + SHIFT + J", hl.dsp.window.move({ direction = "down" }))
hl.bind("SUPER + SHIFT + H", hl.dsp.window.move({ direction = "left" }))
