# --- Cursor ---
cursor            #ffdec7
cursor_text_color #953800

# --- Text ---
foreground            #ffffff
background            #2c4d49

# --- Selection ---
selection_foreground  #000000
selection_background  #87b7c4

# --- URLs ---
url_color             #ffffff

# --- Black ---
color0  #465957
color8  #51615e

# --- Red ---
color1  #b3b780
color9  #e4e5d2

# --- Green ---
color2  #fafdfe
color10 #ffffff

# --- Yellow ---
color3  #e6f8f7
color11 #ffffff

# --- Blue ---
color4  #ff8829
color12 #ffffff

# --- Magenta ---
color5  #05d7ff
color13 #ffffff

# --- Cyan ---
color6  #00f8ed
color14 #ffffff

# --- White ---
color7  #f79c5e
color15 #a84b00

# --- Marks ---
mark1_foreground #000000
mark1_background #ffe0cc
mark2_foreground #000000
mark2_background #c3f0fd
mark3_foreground #000000
mark3_background #aef9f2

# --- Tabs ---
active_tab_foreground   #953800
active_tab_background   #ffdec7
inactive_tab_foreground #ffffff
inactive_tab_background #51615e

# --- Borders ---
active_border_color   #ffffff
inactive_border_color #9fb3b0
