# ~/.config/hypr/modules/input.conf

input {
    kb_layout = us
	kb_options = caps:escape
	
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
        tap-to-click = true
        tap-and-drag = true
        disable_while_typing = true
        scroll_factor = 0.5        # slow scroll down if needed
    }
}

gestures {
    workspace_swipe_invert = false
    workspace_swipe_distance = 300

    gesture = 3, horizontal, workspace
}

device {
    name = elan0712:00-04f3:30fd-touchpad
    enabled = false
}

device {
    name = elan0712:00-04f3:30fd-mouse
    enabled = false
}

device {
    name = usb-optical-mouse-
    sensitivity = 0
    accel_profile = flat
}


