exec-once = waybar 
exec-once = awww-daemon
exec-once = systemctl --user start swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

#cliphist daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
