exec-once = waybar 
exec-once = awww-daemon
exec-once = systemctl --user enable --now swayosd-server

#cliphist daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
