windowrule {
    # Ignore maximize requests from all apps
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}


windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    # Hyprland-run float position
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# Float common utility apps
windowrule {
    name = float-utilities
    match:class = ^(pavucontrol|blueman-manager|nm-connection-editor|Calculator)$
    float = true
    center = true
}

# Float file dialogs
windowrule {
    name = float-file-dialogs
    match:title = ^(Open|Save|Save As|File Picker)(.*)$
    float = true
    center = true
    size = 800 600
}

windowrule {
    name = float-wifi
    match:title = wifi
    float = yes
    center = yes
    size = 800 500
}

windowrule {
    name = float-bluetooth
    match:title = bluetooth
    float = yes
    center = yes
    size = 800 500
}
windowrule {
    name = postimg-browser
    match:title = ^(.*)Google Chrome for Testing(.*)$
    workspace = 7 silent
}

# Waybar Glass Blur Rules
layerrule {
    name = blur
    match:namespace = waybar
}
layerrule {
    name = ignorezero
    match:namespace = waybar
}

# Quickshell Islandbar Blur Rules
layerrule {
    name = blur
    match:namespace = islandbar
}
layerrule {
    name = ignorezero
    match:namespace = islandbar
}

# PCManFM Acrylic Transparency & Blur Rule
windowrule {
    name = pcmanfm-transparency
    match:class = ^(pcmanfm)$
    opacity = 0.85 override 0.85 override
    no_dim = on
}

# Dolphin Acrylic Transparency & Blur Rule
windowrule {
    name = dolphin-blur
    match:class = ^(org.kde.dolphin)$
    blur = on
}
windowrule {
    name = dolphin-transparency
    match:class = ^(org.kde.dolphin)$
    opacity = 0.85 override 0.85 override
    no_dim = on
}


